services:
  web:
    image: volare-dev:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        MIX_ENV: ${MIX_ENV:-dev}
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/volare_dev
      SECRET_KEY_BASE: cQ3VLNX5nkxRgQC4idmVfHYnzf51KkFFp4ACZuIBT61in2cWWbWpkEYDx2RQiPFz
      PHX_HOST: dev.volareee.com
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - .:/app:cached
    command: iex -S mix phx.server
    stdin_open: true
    tty: true

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: volare_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
   pgdata:
